### ISSUE TITLE
Static Server for TodoMVC Common Files or CDN?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/riotjs2-todomvc#3]
Are the files available from CDN?

**Comment by kumarshantanu** [comment]
Should this question go to https://github.com/tastejs/todomvc or https://github.com/tastejs/todomvc-app-css as they maintain the files?

**Comment by nelsonic** [comment]
@kumarshantanu good question, yes. those repositories would be a better place to ask/check. 👍
